BookStoreWebApp/BookStoreWebApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStoreWebApp.ProductServiceReference;
using ModelPoco;
using BookSaleWebsite;


namespace BookStoreWebApp.Controllers
{
    public class ProductController : Controller
    {
        
        RepositoryOf_ProductClient productClient;
        public ProductController()
        {
            productClient = new RepositoryOf_ProductClient();
        }
        // GET: Product
        public ActionResult Index()
        {
            List<Product> allProducts = productClient.GetAll().ToList();
            return View(allProducts);
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            Product product = productClient.Find(id);
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(Product product)
        {
            try
            {
                // TODO: Add insert logic here
                productClient.Add(product);                                             

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Index");
            }
        }
        

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            Product product = productClient.Find(id);
            return View(product);
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Product product)
        {
            try
            {
                // TODO: Add update logic here
                productClient.Update(product);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            Product product = productClient.Find(id);
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                Product productToDelete = new Product() { ProductID = id };
                // TODO: Add delete logic here
                productClient.Delete(productToDelete);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }


        }

        public ActionResult Buy(int id, Product product)
        {
            return View();
        }

      
    }
}

BookStoreWebApp/BookStoreWebApp/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStoreWebApp.ProductServiceReference;
using BookStoreWebApp.ShoppingServiceReference;
using ModelPoco;
using BookSaleWebsite;

namespace BookStoreWebApp.Controllers
{

    public class ShoppingCartController : Controller
    {
        private BookSaleEntities book = new BookSaleEntities();
        
        public ActionResult Index()
        {
            return View("Index");
        }

        private int Existing(int id) 
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Pr.ProductID == id)
                    return i;
            return -1;
        }

        public ActionResult Delete(int id)
        {
            int index = Existing(id);
            List<Item> cart = (List<Item>)Session["cart"];           


            if (cart[index].Quantity == 1)
            {
                cart.RemoveAt(index);
            }
           else if (cart[index].Quantity >= 1)
            {
                cart[index].Quantity--;
            }                   

          
            Session["cart"] = cart;

            Logger.WriteToLog("An Item Deleted");

            return View("Cart");
        }

        public ActionResult Cart(int id)
        {
            if (Session["cart"] == null)
            {

                List<Item> cart = new List<Item>();
                cart.Add(new Item(book.Products.Find(id), 1));
                Session["cart"] = cart;
            }
            else
            {
                
                List<Item> cart = (List<Item>)Session["cart"];
                int index = Existing(id);
                if (index == -1)
                    cart.Add(new Item(book.Products.Find(id), 1));
                else
                    cart[index].Quantity++;
                Session["cart"] = cart;
            }

            Logger.WriteToLog("An Item Bought");

            return View("Cart");
        }

    }
}

BookStoreWebApp/BookStoreWebApp/Views/ShoppingCart/Cart.cshtml
@{
    ViewBag.Title = "Cart";
}
@using BookStoreWebApp.Controllers
<h2>Cart</h2>

<table class="table">
    <tr>

        <th>
            Title

        </th>
        <th>
            Author

        </th>
        <th>
            Price
        </th>
        <th>
            Quantity
        </th>
        <th>
            Subtotal
        </th>
        <th></th>
    </tr>
    @{
        decimal s = 0;
    }
    @foreach (Item item in (List<Item>)Session["cart"])
    {
        s = s + item.Pr.Price * item.Quantity;

        <tr>

            <td>
                @item.Pr.Title

            </td>
            <td>
                @item.Pr.Author

            </td>

            <td>
                @item.Pr.Price
            </td>
            <td>
                @item.Quantity
            </td>
            <td>
                @(item.Pr.Price * item.Quantity)
            </td>
            <td>
               
                @*@Html.ActionLink("Details", "Details", "Product", new { id = item.Pr.ProductID }, null) |*@
                @Html.ActionLink("Delete", "Delete", "ShoppingCart", new { id = item.Pr.ProductID }, null) 
            </td>
        </tr>
    }
    <tr>
        <td>
            <p><a class="btn btn-default">Total </a></p> 
        </td>
        <td> </td>
        <td> </td>
        <td> </td>
        <td>@s</td>
    </tr>
</table>
<br />
@Html.ActionLink("Continue Shopping", "Index", "Product")
 

BookStoreWebApp/BookStoreWebApp/Views/ShoppingCart/Delete.cshtml
@model ModelPoco.ShoppingCart

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShoppingCart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubTotal)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookStoreWebApp/BookStoreWebApp/Views/ShoppingCart/Index.cshtml
@model ModelPoco.ShoppingCart

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>